# Generated by Django 3.1.1 on 2020-09-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BagContents',
            new_name='BagContent',
        ),
    ]
