# Generated by Django 3.1.1 on 2020-09-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0006_bagcontent_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='bag_owner',
            new_name='owner',
        ),
    ]
