# Generated by Django 3.1.1 on 2020-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0009_auto_20200925_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
